### ISSUE TITLE
Problems with forward searching under Windows

### ISSUE THREAD

**Issue by frankruegamer** [vim-latex/vim-latex#88]
#### Issue
While viewing a PDF on Windows is working fine, forward searching isn't.

#### Description
My viewer, SumatraPDF, shows the error message _Error loading PDF file_ when trying to forward search using `<leader>ls`. Upon investigation, vim-latex seems to escape spaces in the filename when passing the cmd-line argument, e.g. _Google\ Drive_, which conflicts with regular (Windows) folder separation slashes, e.g. _C:\Google\ Drive_.
However escaping isn't necessary when surrounding the path in quotes. Calling
`sumatrapdf "C:\Google Drive\doc.pdf" -forward-search "C:\Google Drive\doc.tex" 25`
works just fine for me.

#### Solution
Fix the generation of path strings for Windows.
My workaround was to remove `fnameescape()` for `mainfnameFull` and `sourcefileFull` in `compiler.vim\Tex_ForwardSearchLaTeX()`.
I'm sure there is a better way.

**Comment by gerw** [comment]
Thank you for the report. Can you also upload your patch?

**Comment by frankruegamer** [comment]
Here is the diff:
```Diff
diff --git a/ftplugin/latex-suite/compiler.vim b/ftplugin/latex-suite/compiler.vim
index 65cd33a..142177d 100644
--- a/ftplugin/latex-suite/compiler.vim
+++ b/ftplugin/latex-suite/compiler.vim
@@ -348,10 +348,10 @@ function! Tex_ForwardSearchLaTeX()
 	let l:origdir = fnameescape(getcwd())
 
 	let mainfnameRoot = fnameescape(fnamemodify(Tex_GetMainFileName(), ':t:r'))
-	let mainfnameFull = fnameescape(Tex_GetMainFileName(':p:r'))
+	let mainfnameFull = Tex_GetMainFileName(':p:r')
 	let target_file = mainfnameFull . "." . s:target
 	let sourcefile = fnameescape(expand('%'))
-	let sourcefileFull = fnameescape(expand('%:p'))
+	let sourcefileFull = expand('%:p')
 	let linenr = line('.')
 	" cd to the location of the file to avoid problems with directory name
 	" containing spaces.
```
As you can see, I didn't change much.
Disclaimer: I have only tested this on Windows and on my machine; I am no Vim expert

**Comment by frankruegamer** [comment]
I tested it on Linux and it seems to work fine.

**Comment by gerw** [comment]
This fix will not work in linux, if you have a directory containing spaces (this is the actual reason for `fnameescape`).

**Comment by gerw** [comment]
I have pushed a commit which should fix your issue. Can you confirm if that helps?

**Comment by mjezzini** [comment]
I was having the same problem. The expand did not solve the problem in my case.  I solved the problem in my case by changing

ftplugin/latex-suite/compiler.vim, line 371 from
'
let execString .= Tex_Stringformat('start %s %s -forward-search %s %s', viewer, target_file, sourcefileFull, linenr)
'

To
`
let target_filew = substitute(target_file, "'", "\"", "g")
let sourcefileFullw = substitute(sourcefileFull, "'", "\"", "g")
let execString .= Tex_Stringformat('start %s %s -forward-search %s %s', viewer, target_filew, sourcefileFullw, linenr)
`
The problem was the use of '\filepath' instead of "\filepath"

**Comment by gerw** [comment]
Did you try the latest version? Can you enable debugging
````
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
````
and show the result of `Tex_ViewLaTeX: execString =...`?

**Comment by mjezzini** [comment]
Yes, I did try the last version. Without my changes I get in the log file 

> comp : Tex_ViewLaTeX: execString = start SumatraPDF -reuse-instance "main.pdf"

> comp : Tex_ForwardSearchLaTeX: execString = silent! !start SumatraPDF -reuse-instance 'U:/GitHub/IEEEXtalk/main.pdf' -forward-search 'U:/GitHub/IEEEXtalk/sec/validation.tex' 13

\ls makes SumatraPDF show the next error 

> Error loading U:\GitHub\IEEEXtalk\'U:\GitHub\IEEEXtalk\main.pd'

After the changes I made the Tex_ViewLaTex keeps the same, but now

> comp : Tex_ForwardSearchLaTeX: execString = silent! !start SumatraPDF -reuse-instance "U:/GitHub/IEEEXtalk/main.pdf" -forward-search "U:/GitHub/IEEEXtalk/sec/crosstalk.tex" 32

And the forward search works

**Comment by gerw** [comment]
Did you try to change the value of `shellslash`? With `shellslash=0`, vim should automatically enclose the string in double quotes.

**Comment by mjezzini** [comment]
I commented the line 
`set shellslash`
in my vimrc and the forward search works! I placed that line in the vimrc based on the [documentation](http://vim-latex.sourceforge.net/documentation/latex-suite/recommended-settings.html)

> " IMPORTANT: win32 users will need to have 'shellslash' set so that latex
> " can be called correctly.
> set shellslash

But I guess is not really necessary

Thanks!

**Comment by gerw** [comment]
I do not know. Maybe that behaviour also depends on your setting of `shell`.
